- name: install pip
  yum: pkg=python-pip

- name: install python packages
  command: pip install --upgrade {{ item }}
  with_items:
    - pip==9.0.1
    - python-dateutil==2.5.2
    - python-etcd==0.4.3
    - docker-py==1.8.0
    - psutil==4.1.0
    - requests==2.11.1
  register: result
  changed_when: "'Successfully installed' in result.stdout"

- name: install lainctl
  command: pip install git+https://github.com/laincloud/lainctl.git@v2.0.1#egg=lain_admin_cli
  when: bootstrapping is defined and bootstrapping|bool
